### ISSUE TITLE
Couldn't find any encrypted method.

### ISSUE THREAD

**Issue by Mecca21** [SychicBoy/NetReactorSlayer#12]
i keep getting this error when i run the program

error 

  [✓] 11/11 Modules loaded...
  [!] Couldn't find any encrypted method.
  [!] Couldn't found any equations, looks like there's no control flow obfuscation applied to methods.
  [!] Couldn't find anti tamper method.
  [!] Couldn't find anti debugger method.
  [!] Couldn't find any proxied call.
  [!] Couldn't find any hidden call.
  [!] Couldn't find any encrypted string.
  [!] Couldn't find any encrypted resource.
  [!] Couldn't find any embedded assembly (DNR).
  [✓] 1 Embedded assemblies dumped (Costura.Fody).
  [!] Couldn't found any encrypted token.

**Comment by SychicBoy** [comment]
I don't recommend to compile the project yourself because the project is currently under maintenance, wait for a stable release.
Also you can send me the target file on [Telegram](https://t.me/SychicBoy), I'll check it.
