### ISSUE TITLE
Deobfuscation info....

### ISSUE THREAD

**Issue by Deltafox79** [SychicBoy/NETReactorSlayer#17]
Hi mr SycicBoy

on this target whit latest v3.0.0.0 :

https://mega.nz/file/n01l2TDJ#671mPggfXRmNU8evhFkXBPvx-emHb5aY8FSSUJ081hI

https://www.mipony.net

**Protettore: Eziriz .NET Reactor(6.x.x.x)[By Dr.FarFar]**

I'm unable to obtain a startable exe.. 
1) whit all option enable exe run and block whitout any message, 
2) whit only deobfuscate control flow the exe give a exception on module entry..

any idea?

Tks..

**Comment by SychicBoy** [comment]
Target protected file contains VM protection and **.NETReactorSlayer** does not yet have the ability to de-virtualize virtualized functions.
Currently I don't have a plan for it but **maybe** in feature I'll develop a de-virtualizer for it.

**Comment by SychicBoy** [comment]
Duplicate of #2
