### ISSUE TITLE
Can this unpack for Net Reactor 4.5-4.7

### ISSUE THREAD

**Issue by tomeroto** [SychicBoy/NetReactorSlayer#2]
Hi friend, I have problem to unpack assembly with detect as below:

![cek](https://user-images.githubusercontent.com/4737601/142716594-ca8474d5-f0a3-4e4e-987f-89ac6cf03ddc.png)

I try to use your tool, and it take no responses:

![cek2](https://user-images.githubusercontent.com/4737601/142716631-8f3f81a7-be8d-4c4c-815b-368be3e0c142.png)

please help

**Comment by SychicBoy** [comment]
It's stuck on "cflow deobfuscation" step, probably target obfuscated assembly is virtualized that's why it's can't invoke arithmetic fields to clean cflow.

**Comment by tomeroto** [comment]
Btw can you unpack for me manually? I will send you assembly. And if it have cost, how much?

**Comment by SychicBoy** [comment]
My contact informations are available in website: www.CodeStrikers.org
