### ISSUE TITLE
Application not working After Deobfuscation

### ISSUE THREAD

**Issue by MQREFP** [SychicBoy/NETReactorSlayer#20]
**Describe the bug**
After using NetReactorSlayer Executable file is not working. I also try it with PreserveAllMDToken and KeepOldMaxStack but problem still there 

**Target obfuscated file**
Archive Password is 123
Download Link is here:-
https://workupload.com/file/Q2kgRpZY3Lv

**OS Version:**
Windows 11 64bit

**Comment by etalejandroet** [comment]
Check --preserve-tokens

**Comment by MQREFP** [comment]
@etalejandroet I used that option but same result.
Problem is symbol renaming. I have used dont-rename option in de4dot modded by mobile46 that works. But this net reactor slayer don't have option for don't-rename.

**Comment by SychicBoy** [comment]
I didn't checked your target file yet, but the new version (v3X) have so many issues, I'll release a fixed version as soon as possible.

**Comment by etalejandroet** [comment]
Yes it would be fine, in version 2.0, there is no problem with Protector Intellilock, but with NetReactor yes
In Version NetReactor 6.8, there must be a problem not finding embedded resources

**Comment by ex1dreamer** [comment]
any chance to find a solution for  de-virtualization?

**Comment by SychicBoy** [comment]
@ex1dreamer de-virtualization feature will be added to **.NETReactorSlayer**, but not now, it's need time.
