### ISSUE TITLE
Failed to Unpack Native Image and Embedded Assemblies 

### ISSUE THREAD

**Issue by MQREFP** [SychicBoy/NETReactorSlayer#22]
**Describe the bug**
This tool fails to unpack native image and embedded assemblies packed by net reactor.

**Target obfuscated file**
Here is the file link:-
Password is 123
https://workupload.com/file/KWGwnkNsc2f

**OS Version:**
Windows 11 64bit

**Comment by SychicBoy** [comment]
There is no problem with `Unpack Native Image` feature, Here is the unpacked image:
https://workupload.com/file/K3GVvJpuvnX | Password: .nrs

Make sure you are using latest version of **.NETReactorSlayer**.
Target file is virtualized so **.NETReactorSlayer** can't fully deobfuscate it.

**Comment by SychicBoy** [comment]
If you need to dump embedded assemblies you can do it manually with tools like [MegaDumper](https://github.com/CodeCracker-Tools/MegaDumper) or [ExtreamDumper](https://github.com/wwh1004/ExtremeDumper).
