### ISSUE TITLE
Anti tamper not working correctly

### ISSUE THREAD

**Issue by vRendevski** [SychicBoy/NETReactorSlayer#23]
**Describe the bug**
Anti tamper doesn't work correctly, whenever I try to open the deobfuscated app it crashes. I have tried running it under a debugger and apparently It crashed because of an exception named "???" and no exception message. I also tried manually removing anti tamper by following what the source code does and this produced the same effect. I believe that this anti-tamper removal method no longer works.

**Target obfuscated file**
I would rather not share the file. I would love to get in contact though, If I could get your Discord that would be great.

**Screenshots**
There isn't much to show, the correct method is removed and all the other features work correctly.

**OS Version:**
Windows 8 64bit

**Additional context**
No additional context.

**Comment by SychicBoy** [comment]
Duplicate of #2
