### ISSUE TITLE
Getting broken methods after deobfuscation

### ISSUE THREAD

**Issue by greenozon** [SychicBoy/NETReactorSlayer#26]
**Describe the bug**
using default parameters, latest release version 4.0.0.0

**Target obfuscated file**
https://www.sendspace.com/file/r4hb4o

**Screenshots**
majority of methods after deobfuscation are not decompiled throwing exception in ILspy, dnSpy
eg:
![image](https://user-images.githubusercontent.com/765343/167917669-0b2b7c71-f9ea-44e8-b557-997df3421852.png)

Reason:
at the method entry the IL code is like follows:

```
		/* 209C0B0000   */ IL_0000: ldc.i4    2972
		/* 2800000006   */ IL_0005: call      <null>
....
```

**OS Version:**
W7x64

**Additional context**
--

**Comment by SychicBoy** [comment]
Thanks for reporting this issue, I'll fix it in next version.

**Comment by SychicBoy** [comment]
> https://www.sendspace.com/file/r4hb4o

There's a problem with download link, please upload file in another website.
