### ISSUE TITLE
StackOverflowException in SimpleDeobfuscator.Deobfuscate on very large methods.

### ISSUE THREAD

**Issue by namidairo** [SychicBoy/NETReactorSlayer#28]
**Describe the bug**
It appears the execution stack is a tad too small and SimpleDeobfuscator.cs will trigger a StackOverflowException within De4dot.Block.BlocksCflowDeobfuscator.Deobfuscate due to recursion exceeding some sort of threshold when attempting to deobfuscate certain methods. (In particular, one very very large method that is apparently ~259k instructions. Looking at the IL, it appears to be a long repeated mess due to what I assume is multiple loops being unrolled.)

While technically a bug within de4dot.blocks, you seem to be shipping it built and the original repo is archived. Additionally, the workaround for the issue can be implemented on your side.

Worked around it by putting the call to deobfuscatorStage.Execute (https://github.com/SychicBoy/NETReactorSlayer/blob/master/NETReactorSlayer.Core/Program.cs#L72) into a thread with an expanded stack size. (May require adjustment)

```c#
Thread deobfThread = new Thread(new ThreadStart(deobfuscatorStage.Execute), (1024 * 1024 * 64));
                    deobfThread.Start();
                    deobfThread.Join();
                    //deobfuscatorStage.Execute();
```

**Target obfuscated file**
Sensitive, can send via Telegram.

**OS Version:**
Win 11 x64

**Screenshots**
![image](https://user-images.githubusercontent.com/1764089/170215661-00934eb7-5d6a-4a93-9b64-668d08532514.png)

**Comment by SychicBoy** [comment]
Hi @namidairo, I must first make sure that your target file is protected by .NET Reactor, Send it via telegram: https://t.me/SychicBoy.

**Comment by SychicBoy** [comment]
> Worked around it by putting the call to deobfuscatorStage.Execute (https://github.com/SychicBoy/NETReactorSlayer/blob/master/NETReactorSlayer.Core/Program.cs#L72) into a thread with an expanded stack size. (May require adjustment)

I'm not sure if this is the right solution, but I tried it and it worked, open a pull request I will probably merge it.

``` c#
var thread = new Thread(deobfuscatorStage.Execute, 1024 * 1024 * 64);
thread.Start();
thread.Join();
while (thread.IsAlive)
    Thread.Sleep(500);
```
