### ISSUE TITLE
dead code left after tool work done

### ISSUE THREAD

**Issue by greenozon** [SychicBoy/NETReactorSlayer#30]
**Describe the bug**
1) Tool did the job smoothly, no errors reported, but the output binary has lots of fake switch/cases etc
are there any chance to clean that out as well? thanks
2) app does not start - throwing this error:
An unhandled exception occurred in x.exe (16728)
Exception: System.TypeInitializationException
Message: The type initializer for xxx threw an exception.
HResult: 0x80131534

**Target obfuscated file**
available

**Screenshots**
![image](https://user-images.githubusercontent.com/765343/176990249-ffa83678-7419-44cf-af25-049385a1d3d5.png)
![image](https://user-images.githubusercontent.com/765343/176990261-7c2e59bc-b2eb-43bf-8b08-255eb8271e0e.png)
![image](https://user-images.githubusercontent.com/765343/176990313-d871788b-d04e-4c0b-90e6-bfd3cb88243e.png)

**OS Version:**
win7 x64

**Additional context**
latest release used version 4.0.0.0

**Comment by greenozon** [comment]
issue 2 as described above it due to call of
public MethodBase ResolveMethod(int metadataToken)
throws this kind of exception...

**Comment by SychicBoy** [comment]
Hi, looks like the problem is about control flow deobfuscation, Send the target file from telegram: https://t.me/SychicBoy
