### ISSUE TITLE
Destination output file location

### ISSUE THREAD

**Issue by greenozon** [SychicBoy/NetReactorSlayer#5]
Is it possible to save the deprotected output file nearby the input one?
for the moment the tool writes into c:\ drive which is not very convenient (and might need admin rights to do so...)

**Comment by SychicBoy** [comment]
The output deobfuscated file always writen next to original file, There is no such a code in Save function to write output file in C:\.

**Comment by greenozon** [comment]
In my case the DNR file was not on C:\ but deep in some paths
but the output file was saved to C:\ (root)
why is that?

**Comment by greenozon** [comment]
I ran it in following path:

![image](https://user-images.githubusercontent.com/765343/143323616-0e277316-7dd0-4d3e-a769-88708b9a8179.png)

![image](https://user-images.githubusercontent.com/765343/143323633-8eb2016b-a6da-4446-9546-afc9dd98d5f9.png)


but output was written over here:

![image](https://user-images.githubusercontent.com/765343/143323655-f35a6357-eb48-4b5a-b5c3-94afcfd73620.png)

**Comment by SychicBoy** [comment]
Contact me on telegram, I'll send you a modified version that ask you for output path.
Telegram: t.me/SychicBoy
