### ISSUE TITLE
GIVING EXCEPTION AFTER DEOBFUSCATION

### ISSUE THREAD

**Issue by MQREFP** [SychicBoy/NETReactorSlayer#50]
**Describe the bug**
FILE GIVING EXCEPTION AFTER DEOBFUSCATION

**Target obfuscated file**
https://workupload.com/file/Kss7CaWttWa
Password is 123

**OS Version:**
Windows 11 22H2 64bit

**Additional context**
Scanner Shows that .Net Reactor 6.x and 4.8-4.9 and Dr.FarFar

**Comment by SychicBoy** [comment]
https://github.com/SychicBoy/NETReactorSlayer/wiki/Documentation#supported-versions
