### ISSUE TITLE
Banner rendering in console

### ISSUE THREAD

**Issue by greenozon** [SychicBoy/NETReactorSlayer#52]
Banner of the tool is not properly rendered in standard cmd.exe console

eg:

![image](https://user-images.githubusercontent.com/765343/207254986-0e55e700-c912-4bc8-8a35-da8f3d4eeb66.png)

ver 6.4.0 from NETReactorSlayer.CLI-net6.0-win64.zip package

**Comment by SychicBoy** [comment]
Changing cmd font should solve the problem.
Also you can use the GUI version instead:
https://github.com/SychicBoy/NETReactorSlayer/releases/download/v6.4.0.0/NETReactorSlayer-netframework.zip
