### ISSUE TITLE
Clean ctor body from DNR leftovers

### ISSUE THREAD

**Issue by greenozon** [SychicBoy/NetReactorSlayer#6]
after using the tool I see some dnr internal methods in lots of ctors, eg:
the first two calls are dot net reactor leftovers....

```
	public Test101()
	{
		z8VqVd2BoDB0euGJcb.IoRGjEXTw();
		hZGJKrMNSweI9iZoJp.urf8l2TrZXBjv();
		base..ctor();
	}
```

PS I see much more DNR leftover code inside assembly body, but not sure if the tool is capable of deleting that too?...

**Comment by SychicBoy** [comment]
That internal methods body erased by **NetReactorSlayer**, there is nothing to worry about it.
In next release I'll add few lines of code to delete that methods from assembly.

**Comment by SychicBoy** [comment]
That internal methods body erased by NetReactorSlayer, there is nothing to worry about it.
In next release I'll add few lines of code to delete that methods from assembly.
