### ISSUE TITLE
Slayed version is still kinda obfuscated

### ISSUE THREAD

**Issue by ahmedfamhy3** [SychicBoy/NETReactorSlayer#61]
**Describe the bug**
When i try to slay .net reactor 6.4 protected file and disable the renaming it ends up like that 
it even look on detect it easy as protected

**Target obfuscated file**
Private

**Screenshots**
![image_2023-02-01_00-09-04](https://user-images.githubusercontent.com/122128503/215997804-3932782a-31d4-4862-b4af-e16a6982c585.jpg)
![image](https://user-images.githubusercontent.com/122128503/215999514-705cc50e-bb82-4baa-960f-7933ddbbaa71.png)

**OS Version:**
Windows 10

**Additional context**

**Comment by SychicBoy** [comment]
Send the file from telegram: t.me/Sychicboy

**Comment by ahmedfamhy3** [comment]
sent it
