### ISSUE TITLE
Couldn't load assembly using reflection.

### ISSUE THREAD

**Issue by D3vil0p3r** [SychicBoy/NETReactorSlayer#93]
I'm using the latest version of the tool on Linux by downloading NETReactorSlayer.CLI-net6.0-linux64.zip

When I run it on a exe file as `NETReactorSlayer-x64.CLI.exe`, I get the following warns:
```
  [INFO] 15/15 Modules loaded...
  [WARN] Couldn't load assembly using reflection.
  [WARN] Couldn't find any encrypted method.
  [WARN] Couldn't find any equation to resolve.
  [WARN] Couldn't find anti tamper method.
  [WARN] Couldn't find anti debugger method.
  [WARN] Couldn't find any proxied call.
  [WARN] Couldn't find any encrypted string.
  [WARN] Couldn't find any encrypted resource.
  [WARN] Couldn't found any obfuscated metadata token.
  [INFO] Renaming obfuscated symbols...
  [WARN] Couldn't find any outline method.
  [INFO] Saved to: NETReactorSlayer.CLI_Slayed.exe
```
Are they expected or am I missing some dependency on my Arch Linux system?

**Comment by D3vil0p3r** [comment]
@SychicBoy

**Comment by greenozon** [comment]
>When I run it on a exe file as NETReactorSlayer-x64.CLI.exe

you are supposed to use .netreactor protected assemblies on this tool, 
do you have some?

**Comment by greenozon** [comment]
For example - you could use the test protected assembly from #92 
Under Ubuntu it shows as follows

![image](https://github.com/user-attachments/assets/6e4e47ab-b0e2-4c16-9307-80fa40144a26)

**Comment by D3vil0p3r** [comment]
Yes, in Arch I get the same by using that .exe
![image](https://github.com/user-attachments/assets/f273482f-69f8-466c-afe8-32853fb11485)

**Comment by greenozon** [comment]
congrats!
well done
+1 OS
